version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      docker: 19

  pre_build:
    commands:
      - echo Installing dependencies
      - npm install

  build:
    commands:
      - echo Building and tagging Docker image
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com
      - docker build -t node-api .
      - docker tag node-api:latest $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/node-api:latest

  post_build:
    commands:
      - echo Pushing to ECR
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/node-api:latest
      - printf '{"imageUri":"%s"}' $AWS_ACCOUNT_ID.dkr.ecr.us-east-1.amazonaws.com/node-api:latest  > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
